### ISSUE TITLE
Some elements have weird dashed outlines

### ISSUE THREAD

**Issue by iamale** [LinxGem33/OSX-Arc-Shadow#8]
![Screenshot](https://user-images.githubusercontent.com/1298948/27066191-f9bed902-500a-11e7-90a7-b4e7a040e6ea.png)

The cause is obvious:

```css
* {
  outline-color: rgba(92, 97, 108, 0.3);
  outline-style: dashed;
  outline-offset: -3px;
  outline-width: 1px;
  outline-radius: 2px; }
```
